{
 "title": "PyNinja metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 2, "y": 1 },
     "targets": [
      {
       "expr": "avg by(node) (cpu_usage_percent)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Load Average (1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "targets": [
      { "expr": "load_average_1m", "legendFormat": "{{node}}" }
     ]
    },
    {
     "title": "Load Average (5m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "targets": [
      { "expr": "load_average_5m", "legendFormat": "{{node}}" }
     ]
    },
    {
     "title": "Load Average (15m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "targets": [
      { "expr": "load_average_15m", "legendFormat": "{{node}}" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "conditions": [
        {
         "evaluator": {
          "params": [
           0,
           0
          ],
          "type": "gt"
         },
         "operator": { "type": "and" },
         "query": {
          "params": []
         },
         "reducer": {
          "params": [],
          "type": "avg"
         },
         "type": "query"
        }
       ],
       "expression": "($A / $B) * 100",
       "reducer": "mean",
       "type": "math"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "conditions": [
        {
         "evaluator": {
          "params": [
           0,
           0
          ],
          "type": "gt"
         },
         "operator": { "type": "and" },
         "query": {
          "params": []
         },
         "reducer": {
          "params": [],
          "type": "avg"
         },
         "type": "query"
        }
       ],
       "expression": "($A / $B) * 100",
       "reducer": "mean",
       "type": "math"
      }
     ]
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Disk Usage (used)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Disk Usage (free)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Disk Total (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(node) (disk_total_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum by(node) (disk_used_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Free (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum by(node) (disk_free_bytes)", "legendFormat": "__auto" }
   ]
  }
 ]
}