services:
  pyobservability:
    image: thevickypedia/pyobservability
    container_name: observability
    environment:
      CONFIG_FILE: "${CONFIG_FILE:-settings.json}"
    ports:
      - "${HOST_PORT:-8080}:${CONTAINER_PORT:-8080}"
    volumes:
      # Bind mount for persistent storage and config
      # export DOCKER_VOLUME_STORAGE=$(pwd)
      - "${DOCKER_VOLUME_STORAGE:-$HOME/.observability}/config:/config"
    restart: no
