services:
  pyobservability:
    image: thevickypedia/pyobservability
    container_name: observability
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      # Bind mount for persistent storage and config
      # export DOCKER_VOLUME_STORAGE=$(pwd)
      - "${DOCKER_VOLUME_STORAGE:-$HOME/.observability}/config:/config"
    restart: no
